from .UsuarioCreateView import CrearUsuarioView
from .FamiliarCreateView import CrearFamiliarView
from .PsaludCreateView import CrearPsaludView
from .PacienteCreateView import CrearPacienteView
from .HistclinicaCreateView import CrearHistclinicaView
from .SigvitalesCreateView import CrearSigvitalesView
